version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: steuer-fair-postgres
    environment:
      POSTGRES_DB: steuer_fair
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - steuer-fair-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: steuer-fair-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: steuer_fair
      DB_USER: postgres
      DB_PASSWORD: password
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - steuer-fair-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: steuer-fair-web
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - steuer-fair-network

volumes:
  postgres_data:

networks:
  steuer-fair-network:
    driver: bridge
