name: Build and Push Docker Images on Release

on:
  release:
    types: [published]

env:
  DOCKERHUB_USERNAME: tilothiele
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/steuer-fair-api
            ${{ env.DOCKERHUB_USERNAME }}/steuer-fair-web
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/api
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/steuer-fair-api:${{ github.event.release.tag_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/web
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/steuer-fair-web:${{ github.event.release.tag_name }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create summary
        run: |
          echo "## Docker Images Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **API Image**: \`${{ env.DOCKERHUB_USERNAME }}/steuer-fair-api:${{ github.event.release.tag_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Web Image**: \`${{ env.DOCKERHUB_USERNAME }}/steuer-fair-web:${{ github.event.release.tag_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Images are now available on Docker Hub: https://hub.docker.com/r/${{ env.DOCKERHUB_USERNAME }}/"
